version: "3.8"
services:
  java-maven-tomcat:
    image: mcr.microsoft.com/vscode/devcontainers/java:0-8
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /workspace/.m2
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - MAVEN_HOME=/usr/share/maven
      - CATALINA_HOME=/opt/tomcat
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    command: >
      bash -c "
        wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.0/bin/apache-tomcat-8.5.0.tar.gz &&
        tar -xvzf apache-tomcat-8.5.0.tar.gz &&
        mv apache-tomcat-8.5.0 /opt/tomcat &&
        /opt/tomcat/bin/startup.sh"
    
  mariadb:
    image: mariadb:11.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
    driver: local
